# Generated by Django 6.0.5 on 2026-05-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasksfield', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
