# Generated by Django 6.0.5 on 2026-05-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapp', '0003_alter_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
