# Generated by Django 6.0.5 on 2026-05-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksapp', '0004_remove_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.CharField(default='', max_length=10),
        ),
    ]
